# Security Scanning Workflow
# Requirements: 11b.2, 11g.4, 11g.5
#
# This workflow performs comprehensive security scanning on template artifacts.
# Can be called from other workflows or run on schedule.

name: Security Scan

on:
  workflow_call:
    inputs:
      scan_path:
        description: 'Path to scan'
        required: true
        type: string
      scan_type:
        description: 'Type of scan (toolchain or infra-base)'
        required: true
        type: string
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      scan_path:
        description: 'Path to scan'
        required: false
        default: '.'
        type: string

jobs:
  # ==========================================================================
  # Vulnerability Scanning
  # ==========================================================================
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ inputs.scan_path || '.' }}
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          ignore-unfixed: true

      - name: Upload Trivy FS Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'
          category: 'trivy-filesystem'

      - name: Run Trivy (Config)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: ${{ inputs.scan_path || '.' }}
          format: 'sarif'
          output: 'trivy-config-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy Config Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-config-results.sarif'
          category: 'trivy-config'

  # ==========================================================================
  # Infrastructure as Code Scanning
  # ==========================================================================
  iac-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.scan_path || '.' }}
          format: sarif
          soft_fail: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.scan_path || '.' }}
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true

      - name: Upload Checkov Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'checkov-results.sarif'
          category: 'checkov'

  # ==========================================================================
  # Container Image Scanning (if applicable)
  # ==========================================================================
  container-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    if: inputs.scan_type == 'toolchain'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: find-dockerfiles
        run: |
          DOCKERFILES=$(find ${{ inputs.scan_path || '.' }} -name 'Dockerfile' -type f | tr '\n' ' ')
          echo "dockerfiles=${DOCKERFILES}" >> $GITHUB_OUTPUT

      - name: Build and Scan Images
        if: steps.find-dockerfiles.outputs.dockerfiles != ''
        run: |
          for dockerfile in ${{ steps.find-dockerfiles.outputs.dockerfiles }}; do
            dir=$(dirname "$dockerfile")
            name=$(basename "$dir")
            echo "Building and scanning ${name}..."
            docker build -t "scan-${name}:latest" -f "$dockerfile" "$dir"
            
            # Scan with Trivy
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              aquasec/trivy:latest image \
              --severity CRITICAL,HIGH \
              --exit-code 0 \
              "scan-${name}:latest"
          done

  # ==========================================================================
  # SBOM Generation
  # Requirement 11g.4: Produce artifacts with SBOM generation
  # ==========================================================================
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX)
        run: |
          syft ${{ inputs.scan_path || '.' }} -o spdx-json > sbom-spdx.json

      - name: Generate SBOM (CycloneDX)
        run: |
          syft ${{ inputs.scan_path || '.' }} -o cyclonedx-json > sbom-cyclonedx.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom-spdx.json
            sbom-cyclonedx.json

  # ==========================================================================
  # Secret Scanning
  # ==========================================================================
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ${{ inputs.scan_path || '.' }}
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified

  # ==========================================================================
  # Summary Report
  # ==========================================================================
  summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [vulnerability-scan, iac-scan, sbom, secret-scan]
    if: always()
    steps:
      - name: Generate Summary
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Vulnerability Scan | ${{ needs.vulnerability-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| IaC Scan | ${{ needs.iac-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| SBOM Generation | ${{ needs.sbom.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Secret Scan | ${{ needs.secret-scan.result }} |" >> $GITHUB_STEP_SUMMARY
