# Toolchain Template CI/CD Pipeline
# Requirements: 11b.1, 11b.2, 11b.4, 11f.3, 11f.4
#
# This workflow validates, tests, and publishes toolchain templates.
# Copy this file to .github/workflows/ in your toolchain templates repository.

name: Toolchain Template CI

on:
  push:
    branches: [main, beta/*, release/*]
    paths:
      - 'toolchains/**'
      - '.github/workflows/toolchain-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'toolchains/**'
  workflow_dispatch:
    inputs:
      toolchain:
        description: 'Toolchain to build (leave empty for all)'
        required: false
        type: string

env:
  TERRAFORM_VERSION: '1.6.0'
  GO_VERSION: '1.21'

jobs:
  # ==========================================================================
  # Stage 1: Validation and Linting
  # Requirement 11f.3: Validate templates locally before publishing
  # ==========================================================================
  validate:
    name: Validate Toolchain Templates
    runs-on: ubuntu-latest
    outputs:
      changed_toolchains: ${{ steps.changes.outputs.toolchains }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changed Toolchains
        id: changes
        run: |
          if [ -n "${{ github.event.inputs.toolchain }}" ]; then
            echo "toolchains=${{ github.event.inputs.toolchain }}" >> $GITHUB_OUTPUT
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^toolchains/' | cut -d'/' -f2 | sort -u | tr '\n' ' ')
            echo "toolchains=${CHANGED:-all}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Validate YAML Syntax
        run: |
          for toolchain in toolchains/*/; do
            if [ -f "${toolchain}toolchain.yaml" ]; then
              echo "Validating ${toolchain}toolchain.yaml"
              python3 -c "import yaml; yaml.safe_load(open('${toolchain}toolchain.yaml'))"
            fi
          done

      - name: Validate Terraform Syntax
        run: |
          for toolchain in toolchains/*/; do
            echo "Validating Terraform in ${toolchain}"
            terraform -chdir="${toolchain}" init -backend=false
            terraform -chdir="${toolchain}" validate
          done

      - name: Contract Validation
        run: |
          # Validate toolchain templates against contract schema
          ./scripts/contract-check.sh toolchains/

      - name: Lint Check
        run: |
          # Run tflint on Terraform files
          for toolchain in toolchains/*/; do
            echo "Linting ${toolchain}"
            tflint --chdir="${toolchain}" || true
          done

  # ==========================================================================
  # Stage 2: Security Scanning
  # Requirement 11b.2: Security scanning for dependencies
  # ==========================================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'toolchains/'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: toolchains/
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true

      - name: Upload Checkov Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'checkov-results.sarif'

  # ==========================================================================
  # Stage 3: Build Artifacts
  # ==========================================================================
  build:
    name: Build Toolchain Artifacts
    runs-on: ubuntu-latest
    needs: [validate, security-scan]
    strategy:
      matrix:
        toolchain: [swdev-toolchain, windev-toolchain, datasci-toolchain]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container Image (if Dockerfile exists)
        if: hashFiles(format('toolchains/{0}/Dockerfile', matrix.toolchain)) != ''
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/toolchains/${{ matrix.toolchain }}:${{ github.sha }} \
            -f toolchains/${{ matrix.toolchain }}/Dockerfile \
            toolchains/${{ matrix.toolchain }}/

      - name: Generate SBOM
        run: |
          # Generate Software Bill of Materials
          syft toolchains/${{ matrix.toolchain }}/ -o spdx-json > sbom-${{ matrix.toolchain }}.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.toolchain }}
          path: sbom-${{ matrix.toolchain }}.json

  # ==========================================================================
  # Stage 4: Approval Gate
  # Requirement 11b.4: Platform owner and security approval
  # ==========================================================================
  approval:
    name: Approval Gate
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    environment: 
      name: toolchain-approval
      # Configure this environment in GitHub with required reviewers:
      # - Platform Owner
      # - Security Representative
    steps:
      - name: Approval Checkpoint
        run: |
          echo "Toolchain templates approved for publishing"
          echo "Approved by: ${{ github.actor }}"
          echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # ==========================================================================
  # Stage 5: Publish to Central Catalog
  # Requirement 11f.4: Publish toolchain templates to central catalog
  # ==========================================================================
  publish:
    name: Publish to Catalog
    runs-on: ubuntu-latest
    needs: [approval]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed 's|refs/heads/release/||')
          else
            VERSION="latest"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Push Container Images
        run: |
          for toolchain in swdev-toolchain windev-toolchain datasci-toolchain; do
            if docker images | grep -q "ghcr.io/${{ github.repository_owner }}/toolchains/${toolchain}"; then
              docker tag \
                ghcr.io/${{ github.repository_owner }}/toolchains/${toolchain}:${{ github.sha }} \
                ghcr.io/${{ github.repository_owner }}/toolchains/${toolchain}:${{ steps.version.outputs.version }}
              docker push ghcr.io/${{ github.repository_owner }}/toolchains/${toolchain}:${{ steps.version.outputs.version }}
            fi
          done

      - name: Create Git Tag
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Update Catalog Index
        run: |
          # Update the central catalog index with new toolchain versions
          echo "Publishing toolchain templates to catalog..."
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Commit: ${{ github.sha }}"
          # Add your catalog update logic here

  # ==========================================================================
  # Stage 6: Deploy to Coder (Optional)
  # ==========================================================================
  deploy:
    name: Deploy to Coder
    runs-on: ubuntu-latest
    needs: [publish]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Deploy Templates
        env:
          CODER_URL: ${{ secrets.CODER_URL }}
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
        run: |
          echo "Deploying toolchain templates to Coder..."
          # terraform apply would go here
          echo "Deployment complete"
